import test from "node:test";
import assert from "node:assert/strict";
process.env.SUPABASE_URL||="https://example.supabase.co";process.env.SUPABASE_ANON_KEY||="test";
const {createAdminFeedbackRouter}=await import("./adminFeedbackRoutes.js");

const ticketId="123e4567-e89b-42d3-a456-426614174000",andrewId="223e4567-e89b-42d3-a456-426614174000",victoriaId="323e4567-e89b-42d3-a456-426614174000",otherId="423e4567-e89b-42d3-a456-426614174000";
const chain=(result)=>{const query={select(){return query},eq(){return query},in(){return query},order(){return query},update(){return query},maybeSingle(){return Promise.resolve(result)},then(resolve,reject){return Promise.resolve(result).then(resolve,reject)}};return query};
const handler=(router,method)=>router.stack.find(layer=>layer.route?.path==="/:id"&&layer.route.methods[method]).route.stack[0].handle;
const response=()=>{const out={};out.res={status(value){out.status=value;return this},render(...args){out.render=args;return this},redirect(...args){out.redirect=args;return this}};return out};
const request=(assigneeId,status="in_progress")=>{const flashes=[];return{req:{params:{id:ticketId},body:{status,assigneeId},flash(...args){flashes.push(args)}},flashes}};
function postClient({currentAssignee=null,profile={id:andrewId,display_name:"Andrew Carroll",active:true},updateResult={data:{id:ticketId},error:null},events=[]}={}){return{from(table){if(table==="admin_profiles"){events.push("lookup");return chain({data:profile?[profile]:[],error:null})}const current={data:{id:ticketId,subject:"Broken recipe",assignee_id:currentAssignee},error:null};const builder=chain(current);builder.update=()=>{events.push("update");return chain(updateResult)};return builder}}}

test("all feedback handlers sit behind router-level admin middleware",()=>{const auth=()=>{};const router=createAdminFeedbackRouter({auth});assert.equal(router.stack[0].handle,auth);assert.equal(router.stack.filter(layer=>layer.route).length,3)});
test("invalid workflow input never creates a data client",async()=>{let made=false;const router=createAdminFeedbackRouter({auth(){},createClient(){made=true}});const out=response();await handler(router,"post")({params:{id:"bad"},body:{status:"deleted"},flash(){}},out.res);assert.equal(made,false);assert.equal(out.redirect[0],303)});
test("detail maps full stored names to only Andrew and Victoria in canonical order",async()=>{const profiles=[{id:otherId,display_name:"Pat",active:true},{id:victoriaId,display_name:"Victoria Johnson",active:true},{id:andrewId,display_name:"Andrew Carroll",active:true}];const client={from(table){return chain(table==="admin_profiles"?{data:profiles,error:null}:{data:{id:ticketId,subject:"Ticket"},error:null})}};const router=createAdminFeedbackRouter({auth(){},createClient:()=>client});const out=response();await handler(router,"get")({params:{id:ticketId},accessToken:"token",flash(){}},out.res);assert.deepEqual(out.render[1].admins.map(admin=>admin.display_name),["Andrew","Victoria"])});
test("forged other or inactive assignees fail before update and email",async()=>{for(const profile of [{id:otherId,display_name:"Pat",active:true},null]){const events=[];let emails=0;const router=createAdminFeedbackRouter({auth(){},createClient:()=>postClient({profile,events}),sendEmail:async()=>{emails++}});const {req,flashes}=request(otherId);await handler(router,"post")(req,response().res);assert.deepEqual(events,["lookup"]);assert.equal(emails,0);assert.equal(flashes[0][0],"error")}});
test("new assignment persists before notifying the canonical recipient",async()=>{const events=[];let payload;const router=createAdminFeedbackRouter({auth(){},createClient:()=>postClient({events}),sendEmail:async(value)=>{events.push("email");payload=value;return{sent:true}}});const {req,flashes}=request(andrewId);await handler(router,"post")(req,response().res);assert.deepEqual(events,["lookup","update","email"]);assert.equal(payload.recipient.email,"carroll.andrew@gmail.com");assert.equal(payload.ticketId,ticketId);assert.equal(flashes[0][1],"Submission updated and assignee notified")});
test("reassignment resolves Victoria's full stored name and notifies only her",async()=>{let payload;const profile={id:victoriaId,display_name:"Victoria Johnson",active:true};const router=createAdminFeedbackRouter({auth(){},createClient:()=>postClient({currentAssignee:andrewId,profile}),sendEmail:async(value)=>{payload=value;return{sent:true}}});const {req}=request(victoriaId);await handler(router,"post")(req,response().res);assert.equal(payload.recipient.email,"vhobbs1895@gmail.com")});
test("unassignment and unchanged assignment persist without email",async()=>{for(const [posted,current] of [["",andrewId],[andrewId,andrewId]]){let emails=0;const router=createAdminFeedbackRouter({auth(){},createClient:()=>postClient({currentAssignee:current}),sendEmail:async()=>{emails++;return{sent:true}}});const {req}=request(posted,"done");await handler(router,"post")(req,response().res);assert.equal(emails,0)}});
test("database failure sends no email",async()=>{let emails=0;const router=createAdminFeedbackRouter({auth(){},createClient:()=>postClient({updateResult:{data:null,error:{code:"DB"}}}),sendEmail:async()=>{emails++}});const {req,flashes}=request(andrewId);await handler(router,"post")(req,response().res);assert.equal(emails,0);assert.equal(flashes.at(-1)[1],"The submission could not be updated")});
test("mail failure preserves saved update and shows a distinct warning",async()=>{const events=[];const router=createAdminFeedbackRouter({auth(){},createClient:()=>postClient({events}),sendEmail:async()=>({sent:false,reason:"provider",status:500})});const {req,flashes}=request(andrewId);await handler(router,"post")(req,response().res);assert.equal(events.filter(value=>value==="update").length,1);assert.equal(flashes[0][0],"error");assert.match(flashes[0][1],/updated.*could not be sent/)});
test("unexpected mail exceptions still report that persistence succeeded",async()=>{const events=[];const router=createAdminFeedbackRouter({auth(){},createClient:()=>postClient({events}),sendEmail:async()=>{throw new Error("provider detail")}});const {req,flashes}=request(andrewId);await handler(router,"post")(req,response().res);assert.deepEqual(events,["lookup","update"]);assert.match(flashes[0][1],/^Submission updated/) });
