import test from "node:test";
import assert from "node:assert/strict";
import { buildAssignmentMessage, sendAssignmentEmail } from "./assignmentEmail.js";

const input={ticketId:"123e4567-e89b-42d3-a456-426614174000",subject:"Burnt <toast>",recipient:{email:"carroll.andrew@gmail.com"}};
const env={APP_URL:"https://potluck.example/",RESEND_API_KEY:"secret",ASSIGNMENT_EMAIL_FROM:"Potluck <support@potluck.example>"};
test("assignment message identifies ticket and uses configured canonical URL",()=>{const message=buildAssignmentMessage({...input,env});assert.equal(message.to,input.recipient.email);assert.match(message.subject,/Burnt <toast>/);assert.match(message.subject,/123e4567/);assert.equal(message.ticketUrl,`https://potluck.example/admin/feedback/${input.ticketId}`);assert.match(message.text,new RegExp(message.ticketUrl))});
test("assignment message removes header line breaks from the email subject",()=>{const message=buildAssignmentMessage({...input,subject:"First\r\nBcc: attacker@example.com",env});assert.doesNotMatch(message.subject,/[\r\n]/);assert.match(message.subject,/First Bcc:/)});
test("delivery sends plain text through Resend without exposing configuration in result",async()=>{let call;const result=await sendAssignmentEmail(input,{env,fetchImpl:async(...args)=>{call=args;return{ok:true,status:200}}});assert.deepEqual(result,{sent:true});assert.equal(call[0],"https://api.resend.com/emails");const body=JSON.parse(call[1].body);assert.deepEqual(body.to,[input.recipient.email]);assert.equal(body.from,env.ASSIGNMENT_EMAIL_FROM);assert.match(body.text,/Open the ticket/)});
test("absent configuration and provider rejection return controlled failures",async()=>{let called=false;assert.deepEqual(await sendAssignmentEmail(input,{env:{},fetchImpl:async()=>{called=true}}),{sent:false,reason:"configuration"});assert.equal(called,false);assert.deepEqual(await sendAssignmentEmail(input,{env,fetchImpl:async()=>({ok:false,status:422})}),{sent:false,reason:"provider",status:422})});
test("network errors and timeout return controlled failures",async()=>{assert.deepEqual(await sendAssignmentEmail(input,{env,fetchImpl:async()=>{throw new Error("secret message")}}),{sent:false,reason:"network"});const result=await sendAssignmentEmail(input,{env,timeoutMs:5,fetchImpl:(_url,{signal})=>new Promise((_,reject)=>signal.addEventListener("abort",()=>reject(Object.assign(new Error("aborted"),{name:"AbortError"}))))});assert.deepEqual(result,{sent:false,reason:"timeout"})});
