import test from "node:test";
import assert from "node:assert/strict";
import { FEEDBACK_ASSIGNEES, filterAssignableAdmins, filterStatuses, isAdminUser, normalizeFilter, normalizeUpdate, resolveAssignmentRecipient } from "./adminUtils.js";

test("only immutable app metadata grants admin",()=>{assert.equal(isAdminUser({app_metadata:{role:"admin"}}),true);assert.equal(isAdminUser({user_metadata:{role:"admin"}}),false)});
test("filters and updates are allowlisted",()=>{assert.equal(normalizeFilter("bad"),"unresolved");assert.deepEqual(filterStatuses("unresolved"),["new","in_progress"]);assert.equal(normalizeUpdate({status:"done",assigneeId:""}).valid,true);assert.equal(normalizeUpdate({status:"bad"}).valid,false)});
test("assignment roster has exact UI names, stored-name aliases, and server-only recipients",()=>{assert.deepEqual(FEEDBACK_ASSIGNEES,[{displayName:"Andrew",profileNames:["Andrew","Andrew Carroll"],email:"carroll.andrew@gmail.com"},{displayName:"Victoria",profileNames:["Victoria","Victoria Johnson"],email:"vhobbs1895@gmail.com"}])});
test("assignable admins map full stored names to canonical labels in canonical order",()=>{const profiles=[{id:"2",display_name:"Victoria Johnson",active:true},{id:"3",display_name:"Pat",active:true},{id:"1",display_name:"Andrew Carroll",active:true}];const admins=filterAssignableAdmins(profiles);assert.deepEqual(admins.map(({display_name})=>display_name),["Andrew","Victoria"]);assert.deepEqual(admins.map(({id})=>id),["1","2"])});
test("missing, inactive, inexact, substring, and duplicate alias profiles are unavailable",()=>{const profiles=[{id:"1",display_name:"Andrew",active:true},{id:"2",display_name:"Andrew Carroll",active:true},{id:"3",display_name:"Victoria Hobbs",active:true},{id:"4",display_name:"Victoria Johnson",active:false},{id:"5",display_name:"Andrew Carroll Jr",active:true}];assert.deepEqual(filterAssignableAdmins(profiles),[])});
test("recipient resolution accepts only active explicit canonical names or aliases",()=>{assert.deepEqual(resolveAssignmentRecipient({display_name:"Andrew Carroll",active:true}),FEEDBACK_ASSIGNEES[0]);assert.deepEqual(resolveAssignmentRecipient({display_name:"Victoria",active:true}),FEEDBACK_ASSIGNEES[1]);assert.equal(resolveAssignmentRecipient({display_name:"Andrew",active:false}),null);assert.equal(resolveAssignmentRecipient({display_name:"Andrew Carroll Jr",active:true}),null);assert.equal(resolveAssignmentRecipient(null),null)});
